# 日志配置
zap:
  level: info # 日志级别
  format: console # 日志格式 json：json模式，否则：文本模式
  prefix: "[github.com/lonevle/gin-server]" # 日志前缀
  director: log # 日志目录 绝对路径或者相对程序路径
  show-line: true # 显示打印日志行号
  # LowercaseLevelEncoder 小写编码器(默认)
  # LowercaseColorLevelEncoder 小写编码器带颜色
  # CapitalLevelEncoder 大写编码器
  # CapitalColorLevelEncoder 大写编码器带颜色
  encode-level: LowercaseColorLevelEncoder # 编码级别
  # 堆栈名称
  stacktrace-key: stacktrace
  log-in-console: true # 日志输出到控制台
  # 日志文件配置
  max-size: 10 # 单个日志文件最大大小
  max-age: 30 # 日志文件最多保存天数
  max-backups: 10 # 日志文件最多保存份数
  compress: false # 是否压缩日志文件

# 系统配置
system:
  addr: 9999
  db-type: sqlite # sqlite(默认)|mysql|sqlserver|postgresql


# sqlite数据库配置
sqlite:
  path: "./" # 数据库文件路径
  port: ""
  config: ""
  db-name: "gs" # 数据库文件名称
  username: ""
  password: ""
  max-idle-conns: 10 # 空闲中的最大连接数
  max-open-conns: 100 # 打开到数据库的最大连接数
  log-mode: "" # 日志级别，默认info
  log-zap: false